package permits

import (
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The real endpoint's shape: contract/permits/snapshot.json, generated by
// the workflow service from the identity service's answer.
func TestHTTPRefresherReadsTheIdentityServicesAnswer(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "..", "contract", "permits", "snapshot.json"))
	if err != nil {
		t.Fatal(err)
	}
	var auth, inm, path string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		auth, inm, path = r.Header.Get("Authorization"), r.Header.Get("If-None-Match"), r.URL.Path+"?"+r.URL.RawQuery
		if inm == `"12"` {
			w.WriteHeader(http.StatusNotModified)
			return
		}
		w.Header().Set("ETag", `"12"`)
		_, _ = w.Write(raw)
	}))
	defer srv.Close()
	h := HTTPRefresher{BaseURL: srv.URL, Token: "tok_k.s"}
	s, err := h.Fetch(context.Background(), "org-a", "cms", 0)
	if err != nil {
		t.Fatal(err)
	}
	if auth != "Bearer tok_k.s" || path != "/api/orgs/org-a/permits?app=cms" || inm != "" {
		t.Fatalf("asked %s with %q, If-None-Match %q", path, auth, inm)
	}
	if s.Version != 12 || len(s.Members) != 2 || !s.Members[1].Staff || s.Org != "org-a" || s.App != "cms" {
		t.Fatalf("snapshot = %+v", s)
	}
	if !Decide(s, "ana@example.test", "cms:page:publish", "org/org-a/cms/team/alpha").Allowed {
		t.Fatal("the vector's statement must decide as written")
	}
	if !Decide(s, "ops@example.test", "orders:order:refund", "org/anyone/orders/order/1").Allowed {
		t.Fatal("staff hold * on *")
	}
	if _, err := h.Fetch(context.Background(), "org-a", "cms", 12); !errors.Is(err, ErrNotModified) {
		t.Fatalf("If-None-Match at the version -> %v", err)
	}
}

func TestHTTPRefresherKeepsTheServicesFailuresApart(t *testing.T) {
	for status, want := range map[int]string{
		http.StatusServiceUnavailable: "could not verify",
		http.StatusUnauthorized:       "not active",
		http.StatusForbidden:          "refused",
		http.StatusNotFound:           "no organisation",
	} {
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(status)
			_, _ = w.Write([]byte(`{"error":"x"}`))
		}))
		_, err := HTTPRefresher{BaseURL: srv.URL, Token: "t"}.Fetch(context.Background(), "org-a", "cms", 0)
		srv.Close()
		if err == nil || !strings.Contains(err.Error(), want) {
			t.Errorf("%d -> %v, want %q", status, err, want)
		}
	}
	if _, err := (HTTPRefresher{BaseURL: "https://x"}).Fetch(context.Background(), "a", "b", 0); !errors.Is(err, ErrUnconfigured) {
		t.Fatalf("no token -> %v", err)
	}
}
